CREATE TABLE ad_account_roas (
  adgroup_id Nullable(String),
  arpu_180d Nullable(Float64),
  arpu_1d Nullable(Float64),
  arpu_30d Nullable(Float64),
  arpu_365d Nullable(Float64),
  arpu_3d Nullable(Float64),
  arpu_7d Nullable(Float64),
  arpu_90d Nullable(Float64),
  campaign_group_id Nullable(String),
  campaign_id Nullable(String),
  date_start Nullable(String),
  date_stop Nullable(String),
  installs Nullable(Int64),
  revenue Nullable(Float64),
  revenue_180d Nullable(Float64),
  revenue_1d Nullable(Float64),
  revenue_30d Nullable(Float64),
  revenue_365d Nullable(Float64),
  revenue_3d Nullable(Float64),
  revenue_7d Nullable(Float64),
  revenue_90d Nullable(Float64),
  spend Nullable(Float64),
  yield_180d Nullable(Float64),
  yield_1d Nullable(Float64),
  yield_30d Nullable(Float64),
  yield_365d Nullable(Float64),
  yield_3d Nullable(Float64),
  yield_7d Nullable(Float64),
  yield_90d Nullable(Float64)
)
ENGINE = Log
