CREATE TABLE ad_account_creation_request (
  id String,
  ad_accounts_currency Nullable(String),
  additional_comment Nullable(String),
  address_in_chinese Nullable(String),
  address_in_local_language Nullable(String),
  business_registration_id Nullable(String),
  chinese_legal_entity_name Nullable(String),
  credit_card_id Nullable(String),
  english_legal_entity_name Nullable(String),
  extended_credit_id Nullable(String),
  is_smb Nullable(UInt8),
  is_test Nullable(UInt8),
  is_under_authorization Nullable(UInt8),
  legal_entity_name_in_local_language Nullable(String),
  oe_request_id Nullable(String),
  official_website_url Nullable(String),
  planning_agency_business_id Nullable(String),
  promotable_app_ids Array(String),
  promotable_page_ids Array(String),
  promotable_urls Array(String),
  status Nullable(String),
  subvertical Nullable(String),
  time_created Nullable(String),
  vertical Nullable(String),
  advertiser_business_id Nullable(String),
  promotable_page_urls Array(String)
)
ENGINE = Log
