CREATE TABLE ad_account_activity (
  id String,
  billing_address_new Nullable(String),
  billing_address_old Nullable(String),
  created_by Nullable(String),
  created_time Nullable(DateTime),
  credit_status_new Nullable(String),
  credit_status_old Nullable(String),
  currency_new Nullable(String),
  currency_old Nullable(String),
  event_time Nullable(String),
  event_type Nullable(String),
  funding_id_new Nullable(String),
  funding_id_old Nullable(String),
  grace_period_time_new Nullable(Int64),
  grace_period_time_old Nullable(Int64),
  manager_id_new Nullable(String),
  manager_id_old Nullable(String),
  name_new Nullable(String),
  name_old Nullable(String),
  status_new Nullable(String),
  status_old Nullable(String),
  terms_new Nullable(Int64),
  terms_old Nullable(Int64),
  tier_new Nullable(String),
  tier_old Nullable(String),
  time_updated_new Nullable(String),
  time_updated_old Nullable(String)
)
ENGINE = Log
