CREATE TABLE ads_action_stats (
  _1d_click Nullable(String),
  _1d_view Nullable(String),
  _28d_click Nullable(String),
  _28d_view Nullable(String),
  _7d_click Nullable(String),
  _7d_view Nullable(String),
  action_canvas_component_id Nullable(String),
  action_canvas_component_name Nullable(String),
  action_carousel_card_id Nullable(String),
  action_carousel_card_name Nullable(String),
  action_converted_product_id Nullable(String),
  action_destination Nullable(String),
  action_device Nullable(String),
  action_event_channel Nullable(String),
  action_link_click_destination Nullable(String),
  action_location_code Nullable(String),
  action_reaction Nullable(String),
  action_target_id Nullable(String),
  action_type Nullable(String),
  action_video_asset_id Nullable(String),
  action_video_sound Nullable(String),
  action_video_type Nullable(String),
  inline Nullable(String),
  interactive_component_sticker_id Nullable(String),
  interactive_component_sticker_response Nullable(String),
  value Nullable(String)
)
ENGINE = Log
