CREATE TABLE conversion_action_query (
  conversion_id Array(String),
  dataset Array(String),
  event Array(String),
  _event_creator Array(String),
  event_type Array(String),
  fb_pixel Array(String),
  fb_pixel_event Array(String),
  leadgen Array(String),
  object Array(String),
  _object_domain Array(String),
  offer Array(String),
  _offer_creator Array(String),
  offsite_pixel Array(String),
  page Array(String),
  _page_parent Array(String),
  post Array(String),
  _post_object Array(String),
  _post_object_wall Array(String),
  _post_wall Array(String),
  question Array(String),
  _question_creator Array(String),
  response Array(String),
  subtype Array(String)
)
ENGINE = Log
